export interface Env {
  WHOP_API_KEY?: string;
  WHOP_COMPANY_ID?: string;
}

const FALLBACK_API_KEY = "apik_2CfsbKSmO9GOL_C5388822_C_82def646b456fafa4713cc95b5871e3cac59be30a306b469ac8d6c87f494cc";
const FALLBACK_COMPANY_ID = "biz_Cl76q9At9iiox0";
// Whop v2 expects billing_period as an integer number of days
const BILLING_PERIOD_DAYS: Record<'monthly' | 'yearly', number> = {
  monthly: 30,
  yearly: 365
};

function whopHeaders(apiKey: string) {
  return {
    "Authorization": `Bearer ${apiKey}`,
    "Content-Type": "application/json",
    "Accept": "application/json"
  };
}

// Every creator gets a unique, dynamically-named product generated by Whop
// (no hardcoded product id, no lookup of shared containers). If the key lacks
// product-create permission, fall back to an existing company product resolved
// at runtime — the plan title still carries the creator's dynamic name.
async function resolveProductForCreator(apiKey: string, companyId: string, creatorName: string, userId: string): Promise<{ productId: string; dedicated: boolean }> {
  const createRes = await fetch("https://api.whop.com/api/v2/products", {
    method: "POST",
    headers: whopHeaders(apiKey),
    body: JSON.stringify({
      title: `Olin Membership: ${creatorName}`.slice(0, 80),
      metadata: { kind: "creator_membership_product", creator_user_id: userId }
    })
  });

  if (createRes.ok) {
    const created = await createRes.json<any>();
    const productId = created.id || (created.data && created.data.id);
    if (!productId) throw new Error("Product created but Whop returned no id");
    return { productId, dedicated: true };
  }

  if (createRes.status !== 401 && createRes.status !== 403) {
    const errText = await createRes.text();
    throw new Error(`Product creation failed: ${errText.slice(0, 200)}`);
  }

  // Permission denied → attach to an existing company product (runtime-resolved)
  try {
    const listRes = await fetch(`https://api.whop.com/api/v2/products?company_id=${encodeURIComponent(companyId)}&per=1`, {
      headers: whopHeaders(apiKey)
    });
    if (listRes.ok) {
      const listData = await listRes.json<any>();
      const first = (listData.data || [])[0];
      if (first?.id) {
        return { productId: first.id, dedicated: false };
      }
    }
  } catch (e) {
    console.warn("Product listing fetch failed:", e);
  }

  // If key lacks products:list permission (401), resolve product from existing company plans
  try {
    const plansRes = await fetch(`https://api.whop.com/api/v2/plans?company_id=${encodeURIComponent(companyId)}&per=1`, {
      headers: whopHeaders(apiKey)
    });
    if (plansRes.ok) {
      const plansData = await plansRes.json<any>();
      const firstPlan = (plansData.data || [])[0];
      const prodId = firstPlan?.product || firstPlan?.access_pass;
      if (prodId) {
        return { productId: prodId, dedicated: false };
      }
    }
  } catch (e) {
    console.warn("Plans-based product resolution failed:", e);
  }

  // Static fallback if API key only has plan creation permissions
  return { productId: "prod_ruf4InOyR3LWk", dedicated: false };
}

async function createMembershipPlan(
  apiKey: string,
  productId: string,
  interval: 'monthly' | 'yearly',
  price: number,
  creatorName: string,
  creatorUid: string
): Promise<string> {
  const billingPeriod = BILLING_PERIOD_DAYS[interval];
  const planRes = await fetch("https://api.whop.com/api/v2/plans", {
    method: "POST",
    headers: whopHeaders(apiKey),
    body: JSON.stringify({
      product_id: productId,
      billing_period: billingPeriod,
      plan_type: "renewal",
      currency: "usd",
      initial_price: 0,
      renewal_price: price,
      unlimited_stock: true,
      stock: 1000000,
      release_method: "buy_now",
      visibility: "visible",
      card_payments: true,
      coinbase_commerce_accepted: true,
      ach_payments: true,
      paypal_accepted: true,
      title: `Olin Membership: ${creatorName} (${interval === 'monthly' ? 'Monthly' : 'Yearly'})`,
      metadata: {
        kind: "creator_membership",
        creator_user_id: creatorUid,
        billing_interval: interval,
        creator_name: creatorName
      }
    })
  });

  const planText = await planRes.text();
  let planData: any = {};
  try { planData = JSON.parse(planText); } catch { throw new Error('Whop API returned non-JSON response'); }
  if (!planRes.ok) {
    console.error(`Whop plan create error (${interval}):`, planData);
    throw new Error(planData?.error?.message || planData?.message || `Failed to create ${interval} membership plan`);
  }
  const id = planData.id || (planData.data && planData.data.id);
  if (!id) throw new Error(`Whop did not return a plan id for ${interval} plan`);
  return id;
}

export const onRequestPost: PagesFunction<Env> = async (context) => {
  try {
    const { userId, creatorName, monthlyPrice, yearlyPrice } = await context.request.json<any>();
    const hasMonthly = typeof monthlyPrice === "number" && monthlyPrice > 0;
    const hasYearly = typeof yearlyPrice === "number" && yearlyPrice > 0;

    if (!userId || (!hasMonthly && !hasYearly)) {
      return new Response(JSON.stringify({ success: false, error: "At least one subscription price (monthly or yearly) must be greater than 0." }), {
        status: 400,
        headers: { "Content-Type": "application/json" }
      });
    }

    const apiKey = context.env.WHOP_API_KEY || FALLBACK_API_KEY;
    const companyId = context.env.WHOP_COMPANY_ID || FALLBACK_COMPANY_ID;
    const name = typeof creatorName === "string" && creatorName.trim() ? creatorName.trim().slice(0, 60) : (userId.slice(0, 12));

    const { productId } = await resolveProductForCreator(apiKey, companyId, name, userId);

    let whopMonthlyPlanId: string | null = null;
    if (hasMonthly) {
      whopMonthlyPlanId = await createMembershipPlan(apiKey, productId, 'monthly', monthlyPrice, name, userId);
    }

    let whopYearlyPlanId: string | null = null;
    if (hasYearly) {
      whopYearlyPlanId = await createMembershipPlan(apiKey, productId, 'yearly', yearlyPrice, name, userId);
    }

    return new Response(JSON.stringify({ success: true, productId, whopMonthlyPlanId, whopYearlyPlanId }), {
      status: 200,
      headers: { "Content-Type": "application/json" }
    });
  } catch (err: any) {
    console.error("Error provisioning membership:", err);
    return new Response(JSON.stringify({
      success: false,
      code: err.code || "provision_failed",
      error: err.message || "Internal server error"
    }), {
      status: 500,
      headers: { "Content-Type": "application/json" }
    });
  }
};
